name: Run Python and Multiline Script

on:
  push:
    branches:
      - main

jobs:
  run_python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run python script
        run: python python.py

  run_multiline_script:
    runs-on: ubuntu-latest
    needs: run_python
    steps:
      - name: Run multiline script
        run: |
          echo "This is a multiline script."
          echo "It can contain multiple commands."
          echo "This script runs after the Python script."
